# --- !Ups

create table "CARS" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "GOS_NUMBER" varchar not null unique,
  "MARK" varchar not null,
  "COLOR" varchar not null,
  "YEAR" int not null
);

# --- !Downs

drop table "CARS" if exists;
